name: alert tests

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Check alert rules
      uses: beatlabs/promtool-github-action@v0.0.2
      with:
        cmd: 'test'
        files: '**/tests.yaml'