name: alert tests

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Check alert rules
      uses: addnab/docker-run-action@v3
      with:
        image: prom/prometheus:v2.47.1
        options: -v ${{ github.workspace }}:/tmp/tests
        run: promtool test rules /tmp/tests/**/tests.yaml